from pyrogram import Client, filters
from pyrogram.types import Message
from pyrogram.enums import ParseMode
import random
import string
from Grabber import user_collection, collection
from Grabber import Grabberu as app 
from Grabber import  SUPPORT_ID

OWNER_ID = 7717913705
# Function to generate a random string of length 5 composed of random letters
def generate_random_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=5))

# Dictionary to store generated waifus
generated_waifus = {}

# Function to handle the waifugen command
@app.on_message(filters.command("waifugen") & filters.user(OWNER_ID))
async def waifugen(client: Client, message: Message):
    print("Entering waifugen function...")  # Debugging line

    try:
        waifu_id = message.command[1]  # Get the waifu ID from the command
        quantity = int(message.command[2])  # Get the quantity from the command
    except (IndexError, ValueError):
        await message.reply_text("Invalid usage. Usage: /waifugen <waifu_id> <quantity>")
        return

    # Fetch the waifu based on the provided ID
    waifu = await collection.find_one({'id': waifu_id})
    if not waifu:
        await message.reply_text("Invalid waifu ID.")
        return

    code = generate_random_code()

    # Store the generated waifu and its details
    generated_waifus[code] = {'waifu': waifu, 'quantity': quantity}

    # Create a clickable link for the user's first name
    user_link = f"<a href='tg://user?id={message.from_user.id}'>{message.from_user.first_name}</a>"

    response_text = (
        f"Generated waifu:\n`\n{code}\n```\n"
        f"Name: {waifu['name']}\nRarity: {waifu['rarity']}\nQuantity: {quantity}\n"
        f"Generated by: {user_link}"  # HTML clickable link
    )

    await message.reply_text(response_text, parse_mode=ParseMode.HTML)

    # Log the waifu generation including the clickable user link
    log_text = (
        f"Waifu generated by user {user_link} (ID: {message.from_user.id}):\n"
        f"Code: {code}\n"
        f"Name: {waifu['name']}\n"
        f"Anime: {waifu['anime']}\n"
        f"Rarity: {waifu['rarity']}\n"
        f"ID: {waifu['id']}\n"
        f"Remaining quantity: {quantity}"
    )
    # Send log to the LOGGER_ID with HTML formatting
    await client.send_message(chat_id=LOGGER_ID, text=log_text, parse_mode=ParseMode.HTML)

# Function to claim a generated waifu
@app.on_message(filters.command("claimwaifu"))
async def claimwaifu(client: Client, message: Message):
    print("Entering claimwaifu function...")  # Debugging line

    code = " ".join(message.command[1:])  # Get the code from the command
    user_id = message.from_user.id
    user_link = f"<a href='tg://user?id={user_id}'>{message.from_user.first_name}</a>"

    if code in generated_waifus:
        details = generated_waifus[code]

        if details['quantity'] > 0:
            waifu = details['waifu']

            # Update the user's characters collection
            await user_collection.update_one(
                {'id': user_id},
                {'$push': {'characters': waifu}}
            )

            # Decrement the remaining quantity
            details['quantity'] -= 1

            # Remove the code if its quantity is 0
            if details['quantity'] == 0:
                del generated_waifus[code]

            response_text = (
                f"Congratulations {user_link}! You have received a new waifu for your harem 💍!\n"
                f"Name: {waifu['name']}\n"
                f"Anime: {waifu['anime']}\n"
                f"Rarity: {waifu['rarity']}\n"
                f"ID: {waifu['id']}\n"
            )
            await message.reply_photo(photo=waifu['img_url'], caption=response_text, parse_mode=ParseMode.HTML)

            # Log the waifu claim including the clickable user link
            log_text = (
                f"Waifu claimed by user {user_link} (ID: {user_id}):\n"
                f"Code: {code}\n"
                f"Name: {waifu['name']}\n"
                f"Rarity: {waifu['rarity']}\n"
                f"Remaining quantity: {details['quantity']}"
            )
            # Send log to the LOGGER_ID with HTML formatting
            await client.send_message(chat_id=LOGGER_ID, text=log_text, parse_mode=ParseMode.HTML)
        else:
            await message.reply_text("This code has already been claimed the maximum number of times.")
    else:
        await message.reply_text("Invalid code.")
