import random
import string
from pyrogram import filters, enums, types
from Grabber import app, user_collection, collection, OWNER_ID, SUPPORT_ID, LOGGER

# Function to generate a random string of length 5 composed of random letters
def generate_random_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=5))

# Dictionary to store generated waifus
generated_waifus = {}

# Function to handle the waifugen command
@app.on_message(filters.command("waifugen") & filters.user(OWNER_ID))
async def waifugen(_, message: types.Message):
    if len(message.command) != 3:
        await message.reply_text("Invalid usage. Usage: `/waifugen <waifu_id> <quantity>`", parse_mode=enums.ParseMode.MARKDOWN)
        return

    try:
        waifu_id = message.command[1]  # Get the waifu ID from the command
        quantity = int(message.command[2])  # Get the quantity from the command
    except ValueError:
        await message.reply_text("Invalid quantity. Please enter a number.")
        return

    # Fetch the waifu based on the provided ID
    waifu = await collection.find_one({'id': waifu_id})
    if not waifu:
        await message.reply_text("Invalid waifu ID.")
        return

    code = generate_random_code()

    # Store the generated waifu and its details
    generated_waifus[code] = {'waifu': waifu, 'quantity': quantity}

    response_text = (
        f"Generated waifu:\n`{code}`\n\n"
        f"Name: {waifu['name']}\nRarity: {waifu['rarity']}\nQuantity: {quantity}\n"
        f"Generated by: {message.from_user.mention}"
    )

    await message.reply_text(response_text, parse_mode=enums.ParseMode.HTML)

    # Log the waifu generation
    log_text = (
        f"Waifu generated by {message.from_user.mention} (ID: `{message.from_user.id}`):\n"
        f"Code: `{code}`\n"
        f"Name: {waifu['name']}\n"
        f"Anime: {waifu['anime']}\n"
        f"Rarity: {waifu['rarity']}\n"
        f"ID: `{waifu['id']}`\n"
        f"Initial quantity: {quantity}"
    )
    # Send log to the SUPPORT_ID with HTML formatting
    try:
        await app.send_message(chat_id=SUPPORT_ID, text=log_text, parse_mode=enums.ParseMode.HTML)
    except Exception as e:
        LOGGER.error(f"Log sending failed: {e}")

# Function to claim a generated waifu
@app.on_message(filters.command("claimwaifu"))
async def claimwaifu(_, message: types.Message):
    if len(message.command) < 2:
        await message.reply_text("Usage: `/claimwaifu <code>`", parse_mode=enums.ParseMode.MARKDOWN)
        return

    code = message.command[1]
    user_id = message.from_user.id

    if code in generated_waifus:
        details = generated_waifus[code]

        if details['quantity'] > 0:
            waifu = details['waifu']

            # Update the user's characters collection
            await user_collection.update_one(
                {'id': user_id},
                {'$push': {'characters': waifu}},
                upsert=True
            )

            # Decrement the remaining quantity
            details['quantity'] -= 1

            # Remove the code if its quantity is 0
            if details['quantity'] == 0:
                del generated_waifus[code]

            response_text = (
                f"Congratulations {message.from_user.mention}! You have received a new waifu for your harem 💍!\n"
                f"Name: {waifu['name']}\n"
                f"Anime: {waifu['anime']}\n"
                f"Rarity: {waifu['rarity']}\n"
                f"ID: `{waifu['id']}`\n"
            )
            await message.reply_photo(photo=waifu['img_url'], caption=response_text, parse_mode=enums.ParseMode.HTML)

            # Log the waifu claim
            log_text = (
                f"Waifu claimed by {message.from_user.mention} (ID: `{user_id}`):\n"
                f"Code: `{code}`\n"
                f"Name: {waifu['name']}\n"
                f"Rarity: {waifu['rarity']}\n"
                f"Remaining quantity: {details['quantity']}"
            )
            try:
                await app.send_message(chat_id=SUPPORT_ID, text=log_text, parse_mode=enums.ParseMode.HTML)
            except Exception as e:
                LOGGER.error(f"Log sending failed: {e}")
        else:
            await message.reply_text("This code has already been claimed the maximum number of times.")
    else:
        await message.reply_text("Invalid code.")
