import random
import string
from pyrogram import filters, enums, types
from pyrogram.enums import ParseMode
from Grabber.core.utils import md_escape
from Grabber import app, user_collection, collection, OWNER_ID, SUPPORT_ID, LOGGER
from Grabber.core.sessions import create_session, get_session, delete_session

                                                                             
def generate_random_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=5))

                                         
@app.on_message(filters.command("waifugen") & filters.user(OWNER_ID))
async def waifugen(_, message: types.Message):
    if len(message.command) != 3:
        await message.reply_text("Invalid usage. Usage: `/waifugen <waifu_id> <quantity>`", parse_mode=ParseMode.MARKDOWN)
        return

    try:
        waifu_id = message.command[1]
        quantity = int(message.command[2])
    except ValueError:
        await message.reply_text("Invalid quantity. Please enter a number.")
        return

    waifu = await collection.find_one({'id': waifu_id})
    if not waifu:
        await message.reply_text("Invalid waifu ID.")
        return

    code = generate_random_code()

                      
    await create_session(f"gen_{code}", {'waifu': waifu, 'quantity': quantity}, expire_after=86400 * 7)                  

    response_text = (
        f"Generated waifu:\n`{code}`\n\n"
        f"Name: {md_escape(waifu['name'])}\nRarity: {md_escape(waifu['rarity'])}\nQuantity: {quantity}\n"
        f"Generated by: {message.from_user.mention}"
    )

    await message.reply_text(response_text, parse_mode=ParseMode.MARKDOWN)

    log_text = (
        f"Waifu generated by {message.from_user.mention} (ID: `{message.from_user.id}`):\n"
        f"Code: `{code}`\n"
        f"Name: {waifu['name']}\n"
        f"Anime: {waifu['anime']}\n"
        f"Rarity: {waifu['rarity']}\n"
        f"ID: `{waifu['id']}`\n"
        f"Initial quantity: {quantity}"
    )
    try:
        await app.send_message(chat_id=SUPPORT_ID, text=log_text, parse_mode=ParseMode.MARKDOWN)
    except Exception as e:
        LOGGER.error(f"Log sending failed: {e}")

                                     
@app.on_message(filters.command("claimwaifu"))
async def claimwaifu(_, message: types.Message):
    if len(message.command) < 2:
        await message.reply_text("Usage: `/claimwaifu <code>`", parse_mode=ParseMode.MARKDOWN)
        return

    code = message.command[1]
    user_id = message.from_user.id

                        
    details = await get_session(f"gen_{code}")

    if details:
        if details['quantity'] > 0:
            waifu = details['waifu']

            await user_collection.update_one(
                {'id': user_id},
                {'$push': {'characters': waifu}},
                upsert=True
            )

                                          
            new_quantity = details['quantity'] - 1
            if new_quantity == 0:
                await delete_session(f"gen_{code}")
            else:
                details['quantity'] = new_quantity
                await create_session(f"gen_{code}", details)

            response_text = (
                fr"Congratulations {message.from_user.mention}! You have received a new waifu for your harem 💍\!\n"
                f"Name: {md_escape(waifu['name'])}\n"
                f"Anime: {md_escape(waifu['anime'])}\n"
                f"Rarity: {md_escape(waifu['rarity'])}\n"
                f"ID: `{waifu['id']}`\n"
            )
            await message.reply_photo(photo=waifu['img_url'], caption=response_text, parse_mode=ParseMode.MARKDOWN)

            log_text = (
                f"Waifu claimed by {message.from_user.mention} (ID: `{user_id}`):\n"
                f"Code: `{code}`\n"
                f"Name: {waifu['name']}\n"
                f"Rarity: {waifu['rarity']}\n"
                f"Remaining quantity: {new_quantity}"
            )
            try:
                await app.send_message(chat_id=SUPPORT_ID, text=log_text, parse_mode=ParseMode.MARKDOWN)
            except Exception as e:
                LOGGER.error(f"Log sending failed: {e}")
        else:
            await message.reply_text("This code has already been claimed the maximum number of times.")
    else:
        await message.reply_text("Invalid code.")
