export const RARITY_VISUALS = {
    'Common': { 
        bg: 'bg-zinc-900',
        glow: '',
        text: 'text-zinc-400',
        border: 'border-zinc-800',
        pill: 'bg-zinc-800/50',
    },
    'Medium': { 
        bg: 'bg-emerald-950/20',
        glow: '',
        text: 'text-emerald-400',
        border: 'border-emerald-900/50',
        pill: 'bg-emerald-900/30',
    },
    'Rare': { 
        bg: 'bg-blue-950/20',
        glow: '',
        text: 'text-blue-400',
        border: 'border-blue-900/50',
        pill: 'bg-blue-900/30',
    },
    'Legendary': { 
        bg: 'bg-amber-950/20',
        glow: '',
        text: 'text-amber-400',
        border: 'border-amber-900/50',
        pill: 'bg-amber-900/30',
    },
    'Cosmic': { 
        bg: 'bg-purple-950/20',
        glow: '',
        text: 'text-purple-400',
        border: 'border-purple-900/50',
        pill: 'bg-purple-900/30',
    },
    'Exclusive': { 
        bg: 'bg-rose-950/20',
        glow: '',
        text: 'text-rose-400',
        border: 'border-rose-900/50',
        pill: 'bg-rose-900/30',
    },
    'Limited Edition': { 
        bg: 'bg-orange-950/20',
        glow: '',
        text: 'text-orange-400',
        border: 'border-orange-900/50',
        pill: 'bg-orange-900/30',
    },
    'Royal': { 
        bg: 'bg-cyan-950/20',
        glow: '',
        text: 'text-cyan-400',
        border: 'border-cyan-900/50',
        pill: 'bg-cyan-900/30',
    },
    'Antique': { 
        bg: 'bg-yellow-950/20',
        glow: '',
        text: 'text-yellow-400',
        border: 'border-yellow-900/50',
        pill: 'bg-yellow-900/30',
    },
    'Celestial': { 
        bg: 'bg-zinc-100/5',
        glow: '',
        text: 'text-zinc-100',
        border: 'border-zinc-700',
        pill: 'bg-zinc-800',
    },
    'AMV': {
        bg: 'bg-fuchsia-950/20',
        glow: '',
        text: 'text-fuchsia-400',
        border: 'border-fuchsia-900/50',
        pill: 'bg-fuchsia-900/30',
    },
    'Prestige': {
        bg: 'bg-red-950/30',
        glow: '',
        text: 'text-red-400 font-semibold',
        border: 'border-red-900/50',
        pill: 'bg-red-900/40',
    },
    'Winter': {
        bg: 'bg-sky-950/20',
        glow: '',
        text: 'text-sky-400',
        border: 'border-sky-900/50',
        pill: 'bg-sky-900/30',
    },
    'Summer': {
        bg: 'bg-yellow-950/20',
        glow: '',
        text: 'text-yellow-400',
        border: 'border-yellow-900/50',
        pill: 'bg-yellow-900/30',
    },
    'Valentine': {
        bg: 'bg-pink-950/20',
        glow: '',
        text: 'text-pink-400',
        border: 'border-pink-900/50',
        pill: 'bg-pink-900/30',
    },
    'Halloween': {
        bg: 'bg-orange-950/20',
        glow: '',
        text: 'text-orange-400',
        border: 'border-orange-900/50',
        pill: 'bg-orange-900/30',
    },
};
